### ISSUE TITLE
Error when visualizing atoms objects

### ISSUE THREAD

**Issue by jboes** [jkitchin/vasp#6] opened 2016-05-27 20:08 UTC
Edit: The following code:

```python
from ase.lattice.cubic import FaceCenteredCubic as fcc
from vasp import Vasp

atoms = fcc('Cu',
            directions=[[0, 1, 1],
                        [1, 0, 1],
                        [1, 1, 0]])

calc = Vasp('failed-ase-view',
            xc='PBE',
            kpts=[10, 10, 10],
            encut=250,
            nsw=0,
            atoms=atoms)

calc.calculate()
```

```javascript
: /home-research/jboes/research/tests/failed-ase-view submitted: 1398609.gilgamesh.cheme.cmu.edu
```

```python
from vasp import Vasp
from ase.visualize import view

calc = Vasp('failed-ase-view')
atoms = calc.get_atoms()
view(atoms)
```

Produces the following error:

```javascript
Traceback (most recent call last):
  File "<stdin>", line 25, in <module>
  File "/home-research/jboes/python/ase/ase/visualize/__init__.py", line 49, in view
    write(filename, atoms, format=format)
  File "/home-research/jboes/python/ase/ase/io/formats.py", line 258, in write
    io.write(filename, images, **kwargs)
  File "/home-research/jboes/python/ase/ase/io/trajectory.py", line 310, in write_traj
    trj.write(atoms)
  File "/home-research/jboes/python/ase/ase/io/trajectory.py", line 184, in write
    c.write(prop, x)
  File "/home-research/jboes/python/ase/ase/io/aff.py", line 257, in write
    self.fill(value)
  File "/home-research/jboes/python/ase/ase/io/aff.py", line 195, in fill
    a.tofile(self.fd)
ValueError: cannot write object arrays to a file in binary mode
```

Important notes: As stated below, the view() function works on the atoms object up until the calculation has finished.

**Comment by jkitchin** [comment] 2016-05-27 21:02
heh... is that the simplest example that reproduces the error? I can't even run that since the calculator directories don't exist!

**Comment by jkitchin** [comment] 2016-05-27 21:04
I think this is an ase error. although it happens because of the calculator.

**Comment by jkitchin** [comment] 2016-05-27 21:06
Oddly: this works:

```python
calc.view()
```

**Comment by jboes** [comment] 2016-05-28 20:25
Sorry for posting a useless example. I left it for my own reference so I wouldn't forget about it.

**Comment by devonwa** [comment] 2016-06-23 13:52
As a stopgap, you can remove the calculator to view atoms.

```
atoms = calc.get_atoms()
atoms.set_calculator()
view(atoms)   
``` 

This is useful for manipulation of Atoms objects post-calculation. I'm not sure what all you're losing by doing this, but the atom positions are maintained.

**Comment by jkitchin** [comment] 2016-06-23 15:42
Hopefully this is fixed now.

**Comment by devonwa** [comment] 2016-06-23 16:16
Works for me now.

**Closed** 2016-06-23 16:19 UTC
